# $Id$
#
#  db_orasel Makefile
# 

include ../../Makefile.defs

auto_gen=
NAME=opensips_orasel

include ../../Makefile.sources

DEFS +=-I$(ORAHOME)/include
LIBS +=-L$(ORAHOME)/lib -locci -lclntsh

include ../../Makefile.rules

modules:
