# $Id$
#
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=db_oracle.so

DEFS +=-I$(ORAHOME)/include
LIBS +=-L$(ORAHOME)/lib -locci -lclntsh

include ../../Makefile.modules
